FROM arvanus/cirrusci-flutter:latest

RUN sdkmanager "platforms;android-28" "build-tools;28.0.0" "platforms;android-29" "build-tools;29.0.0" "platforms;android-30" "build-tools;30.0.0" "platforms;android-31" "build-tools;31.0.0"

