name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  #IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: arvanus/cirrusci-flutter
  IMAGE_CACHETAG: ""
  #username: ${{ github.actor }}
  username: arvanus
  password: ${{ secrets.DOCKER_TOKEN }}
  FLUTTER_VERSION: 3.7.12

defaults:
  run:
    working-directory: ./sdk
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag  ${{ env.IMAGE_NAME }}:latest --tag ${{ env.IMAGE_NAME }}:${{ env.FLUTTER_VERSION }} --build-arg flutter_version=${{ env.FLUTTER_VERSION }}
    - name: Docker login
      run: echo ${{ env.password }}  | docker login -u ${{ env.username }}  ${{ env.REGISTRY }} --password-stdin
    - name: Publish Latest
      run: docker push ${{ env.IMAGE_NAME }}:latest
    - name: Publish Version
      run: docker push ${{ env.IMAGE_NAME }}:${{ env.FLUTTER_VERSION }}

  build-cache:
    needs: build
    env:
      IMAGE_CACHETAG: "-cache"
    defaults:
      run:
        working-directory: ./sdk/cache
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag  ${{ env.IMAGE_NAME }}:latest${{env.IMAGE_CACHETAG}} --tag ${{ env.IMAGE_NAME }}:${{ env.FLUTTER_VERSION }}${{env.IMAGE_CACHETAG}} --build-arg flutter_version=${{ env.FLUTTER_VERSION }}
    - name: Docker login
      run: echo ${{ env.password }}  | docker login -u ${{ env.username }}  ${{ env.REGISTRY }} --password-stdin
    - name: Publish Latest
      run: docker push ${{ env.IMAGE_NAME }}:latest${{env.IMAGE_CACHETAG}}
    - name: Publish Version
      run: docker push ${{ env.IMAGE_NAME }}:${{ env.FLUTTER_VERSION }}${{env.IMAGE_CACHETAG}}
